---
abstract: 'A Perl module for accessing the OpenAI API'
author:
  - 'Nelson Ferraz <nferraz@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OpenAI-API
no_index:
  directory:
    - t
    - inc
requires:
  JSON::MaybeXS: '1.004002'
  LWP::UserAgent: '6.47'
  perl: '5.010'
version: 0.07
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
