name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'
        install-modules-args: --with-develop --with-configure

    - run: cpanm --installdeps .
    - run: perl Makefile.PL
    - run: make
    - run: make distcheck
    - run: make test
